version = 0.1
[default.deploy.parameters]
stack_name = "todo-app-stack"
resolve_s3 = true
s3_prefix = "todo-app-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"dev\""
image_repositories = []
